version: '3'
services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

  redis:
    image: redis:latest
    ports:
      - 6379:6379
